import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Manrope } from 'next/font/google'
import { cn } from '@/lib/utils'
import './globals.css'

const fontHeading = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Purpleshares Listing",
  description: "Generated by create next app",
  icons: 'https://www.purpleshares.com/favicon.ico',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={cn(
          'antialiased',
          fontHeading.variable,
          fontBody.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}
